### ISSUE TITLE
引入Log4j2报错

### ISSUE THREAD

**Issue by sukai-cheng** [zhshuixian/learn-spring-boot-2#1]
![image](https://user-images.githubusercontent.com/35868545/80360396-db6a7f00-88b1-11ea-8f21-b909d6069280.png)

**Comment by zhshuixian** [comment]
请问你的Spring Boot 是 2.2.5 版本吗？
可以尝试使用跟 Spring Boot 相同版本的 log4j2 的 starter
```
<!-- https://mvnrepository.com/artifact/org.springframework.boot/spring-boot-starter-log4j2 -->
<dependency>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-log4j2</artifactId>
    <version>2.2.5.RELEASE</version>
</dependency>
```

配置 Maven 使用阿里云的镜像源
[使用阿里云的镜像源](https://zhshuixian.github.io/learn-spring-boot-2/#/00-Introduction?id=_322-maven-%e9%a1%b9%e7%9b%ae)
